hangman_app/guests/__init__.py
from flask import Blueprint

bp_guests = Blueprint("guests", __name__, template_folder='templates')

from hangman_app.guests import routes

hangman_app/guests/routes.py
from sqlalchemy.exc import IntegrityError
import traceback
from hangman_app import db, bcrypt
from flask import current_app, redirect, render_template, flash, request, url_for
from flask_login import current_user, login_user
from hangman_app.models.sql_models import User
from hangman_app.forms.users_forms import SigninForm, LoginForm
from hangman_app.guests import bp_guests
from hangman_app.forms.users_modify import (
    InquiriesUpdateForm,
    PasswordUpdateForm,
)

@bp_guests.route("/signin", methods=["GET", "POST"])
def signin_page():
    if current_user.is_authenticated:
        return redirect(url_for("members.index"))
    
    form = SigninForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(
            user_name=form.user_name.data,
            email=form.email.data,
            password=hashed_password
        )
        db.session.add(user)
        try:
            db.session.commit()
            flash("You have successfully registered! You can now login.", "success")
            return redirect(url_for("guests.login_page"))
        except Exception as e:
            db.session.rollback()
            flash("Registration failed. Please try again.", "danger")
    else:
        for fieldName, errorMessages in form.errors.items():
            for err in errorMessages:
                current_app.logger.debug(f"Error in {fieldName}: {err}")

    return render_template("guests/signin.html", title="Sign in", form=form)





@bp_guests.route("/login", methods=["GET", "POST"])
def login_page():
    if current_user.is_authenticated:
        return redirect(url_for("guests.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_me.data)
            next_page = request.args.get("next")
            return (
                redirect(next_page)
                if next_page
                else redirect(url_for("guests.index"))
            )
        else:
            flash("Login failed. Check email email and password", "danger")
    return render_template("guests/login.html", title="Log in", form=form)


@bp_guests.route("/")
def index():
    if current_user.is_authenticated:
        return render_template("members/index.html")
    else:
        return render_template("guests/index.html")


from hangman_app.utilities.email_utility import send_reset_email


@bp_guests.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("home"))
    form = InquiriesUpdateForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            "An email has been sent to you with instructions to reset your password.",
            "info",
        )
        return redirect(url_for("guests.login_page"))
    return render_template(
        "guests/reset_request.html", title="Reset Password", form=form
    )


@bp_guests.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("The request is invalid or expired", "warning")
        return redirect(url_for("guests.reset_request"))
    form = PasswordUpdateForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated! You can connect", "success")
        return redirect(url_for("guests.login_page"))
    return render_template("guests/reset_token.html", title="Reset Password", form=form)


@bp_guests.route("/create_table")
def create_table():
    try:
        db.create_all()
        return "Progress table created successfully!", 200
    except Exception as e:
        traceback.print_exc()
        return f"An error occurred: {e}", 500


@bp_guests.route("/delete_table")
def delete_table():
    try:
        db.drop_all()
        return "Progress table deleted successfully!", 200
    except Exception as e:
        return f"An error occurred: {e}", 500

hangman_app/templates/guests/index.html
{% extends "base.html" %}

{% block content %}

<style>
    .bg-image {
        background-image: url('/static/page_image/pngegg.png');
        background-position: center calc(5cm + 0px);
        background-repeat: no-repeat;
        background-size: contain;
        background-attachment: fixed;
    }

    .game-title {
        font-size: 72pt;
        text-align: center;
        margin-top: 0cm; /* Adjust this value to position it 3 cm from the top */
    }
</style>

<body class="bg-image">

<h1 class="game-title">HANGMAN GAME</h1>

{% endblock %}

hangman_app/templates/guests/login.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Please login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember_me(class="form-check-input") }}
                    {{ form.remember_me.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('guests.reset_request') }}">Did you forget your password?</a>
                </small>
            </div>
        </form>
    </div>
{% endblock content %}

hangman_app/templates/guests/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

hangman_app/templates/guests/reset_token.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Password change</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirmed_password.label(class="form-control-label") }}
                    {% if form.confirmed_password.errors %}
                        {{ form.confirmed_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirmed_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirmed_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

hangman_app/templates/guests/signin.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="{{ url_for('guests.signin_page') }}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Sign in</legend>
            
            <div class="form-group">
                {{ form.user_name.label(class="form-control-label") }}
                {% if form.user_name.errors %}
                    {{ form.user_name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.user_name.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.user_name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
            <div class="form-group">
                {{ form.confirmed_password.label(class="form-control-label") }}
                {% if form.confirmed_password.errors %}
                    {{ form.confirmed_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirmed_password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirmed_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{{ url_for('guests.login_page') }}">Sign In</a>
    </small>
</div>
{% endblock content %}